### ISSUE TITLE
Fix Bash History

### ISSUE THREAD

**Issue by glowbase** [glowbase/dead_dfir#12]
Bash history doesn't correctly list for some users. 
![image](https://github.com/user-attachments/assets/55ad2c7a-606f-4809-9f95-cfad903e73f9)

**Comment by glowbase** [comment]
@solix414, still doesn't work in some cases. Wondering if you wanted to have a try at fixing this.

**Comment by solix414** [comment]
i'll give it a look yea

**Comment by solix414** [comment]
issue appears to be just because history hasnt been generated yet, just logged in as the postgres user to populate the history file and upon exiting a history file was generated and the script could pick it up, the administrator,,, user is the strange one because it appears to be misreporting postgres as 2 accounts?

**Comment by Incogn1toBro** [comment]
I fixed this issue with the following amendment on line 541

 if [ "$shell" == "zsh" ]; then

**Comment by glowbase** [comment]
The shell of each user needs to be pulled and the history file taken based on this value. Instead of checking purely if the file exists or not.
